config/routes.rb
Rails.application.routes.draw do

  get 'home', to: 'pages#home'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects do
    patch "change_status", on: :member
  end

  resources :patterns, only: [:new, :create, :show, :index, :edit, :update, :destroy]

  resources :shopping_items, only: [:new, :create, :index, :destroy ] do
    patch "toggle_bought", on: :member
  end

  get 'sample-account', to: 'pages#sample_account'  
end

app/views/pages/home.html.erb
<h1>Welcome!</h1>

<div class="home-flex-container" >

  <div class="home-category-card-wrapper">
    <div class="home-category-card-left" >
      <h2>Projects</h2>
      <%= link_to "Add new", new_project_path, class: "btn-basic btn-light-blue-ghost" %>
      <%= link_to "See all", projects_path, class: "btn-basic btn-light-blue-ghost" %>
    </div>
    <%= image_tag "icons/010-sewing-machine.png", class: "home-category-card-right" %>
  </div>

  <div class="home-category-card-wrapper">
    <div class="home-category-card-left" >
      <h2>Patterns</h2>
      <%= link_to "Add new", new_pattern_path, class: "btn-basic btn-light-blue-ghost" %>
      <%= link_to "See all", patterns_path, class: "btn-basic btn-light-blue-ghost" %>
    </div>
    <%= image_tag "icons/008-pattern.png", class: "home-category-card-right" %>
  </div>

  <div class="home-category-card-wrapper">
    <div class="home-category-card-left" >
      <h2>Shopping List</h2>
      <%= link_to "Add new", new_shopping_item_path, class: "btn-basic btn-light-blue-ghost" %>
      <%= link_to "See all", shopping_items_path, class: "btn-basic btn-light-blue-ghost" %>
    </div>
    <%= image_tag "icons/list.png", class: "home-category-card-right" %>
  </div>

</div>

app/views/pages/sample_account.html.erb
<div class="wrapper-pattern-card wrapper-welcome-card">
  <%= image_tag('icons/welcome.png', id: "welcome-icon") %>  
  <div class="align-center small-text">
    <p>
      Thanks for your interest in the Sewing Planner!
    </p>

    <p>
      If you want to check out a sample account which has a couple of sewing patterns and projects already set up, please <%= link_to 'log in', new_user_session_path, target: "_blank", class: "pattern-url-link" %> with the following credentials:
    </p>

    <p>Email: sewingplanner.sample@gmail.com</p>
    <p>Password: 3xampl3$</p>

    <p>
      Or you can start from scratch and create an account <%= link_to 'here', new_user_registration_path, class: "pattern-url-link" %>.
    </p>
  </div>

</div>