config/routes.rb
Rails.application.routes.draw do

  get 'home', to: 'pages#home'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects do
    patch "change_status", on: :member
  end

  resources :patterns, only: [:new, :create, :show, :index, :edit, :update, :destroy]

  resources :shopping_items, only: [:new, :create, :index, :destroy ] do
    patch "toggle_bought", on: :member
  end

  get 'sample-account', to: 'pages#sample_account'  
end

app/models/pattern.rb
class Pattern < ApplicationRecord
  before_destroy :purge_project_images
  include PgSearch::Model
  attr_accessor :delete_photo

  FABRIC_TYPES = %w(Knit Woven)
  has_many :projects, dependent: :destroy
  belongs_to :garment_category
  belongs_to :user
  validates :title, presence: true, uniqueness: { scope: :user_id }
  validates :designer, presence: true
  validates :fabric_type, presence: true, inclusion: { in: FABRIC_TYPES, message: "must be #{FABRIC_TYPES[0..-2].join(", ")} or #{FABRIC_TYPES.last}."  }
  has_one_attached :photo, dependent: :destroy


  pg_search_scope :search_by_title_and_designer, against: [:title, :designer]
  pg_search_scope :filter_by_fabric_type, against: :fabric_type
  pg_search_scope :filter_by_garment_category, associated_against: {
    garment_category: :name }

  def custom_image_tag
    if self.photo.attached?
      image_tag = ActionController::Base.helpers.cl_image_tag self.photo.key
      image_tag.gsub!("<img src=", "").gsub(" />", "")
    else
      "no_image"
    end
  end

  def full_pattern_url
    url = self.pattern_url
    if url.start_with?("https", "http")
      url
    else
      url = "http://" + url
    end
    url
  end

  def shopping_items
    projects = self.projects
    shopping_items = []
    projects.each do |project|
      shopping_items << project.shopping_items
    end
    shopping_items.flatten
  end

  private

  def purge_project_images
    self.projects.each do |project|
      unless !project.photo.attached?
        project.photo.purge
      end
    end
  end
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  before_action :save_referrer, except: [:create, :update]

  def index
    if params[:fabric_type_filter].present?
      @patterns = policy_scope(Pattern).order(garment_category_id: :asc, title: :asc).filter_by_fabric_type("#{params[:fabric_type_filter]}")
    elsif params[:garment_category_filter].present?
      @patterns = policy_scope(Pattern).order(fabric_type: :asc, title: :asc).filter_by_garment_category("#{params[:garment_category_filter]}")
    elsif params[:query].present?
      @patterns = policy_scope(Pattern).order(garment_category_id: :asc, fabric_type: :asc, title: :asc).search_by_title_and_designer("#{params[:query]}")
    else
      @patterns = policy_scope(Pattern).order(garment_category_id: :asc, fabric_type: :asc, title: :asc)
    end
  end

  def new
    @pattern = Pattern.new
    authorize @pattern
  end

  def create
    cleaned_params = clean(pattern_params)
    @pattern = Pattern.new(cleaned_params)
    authorize @pattern
    @pattern.user = current_user

    if @pattern.save
      redirect_to patterns_path+"##{@pattern.id.to_s}", notice: "Pattern successfully created."
    else
      render :new
    end
  end

  def show
    @pattern = Pattern.find(params[:id])
    authorize @pattern

    respond_to do |format|
       format.js
     end
  end

  def edit
    @pattern = Pattern.find(params[:id])
    authorize @pattern
  end

  def update
    @pattern = Pattern.find(params[:id])
    cleaned_params = clean(pattern_params)
    @pattern.assign_attributes(cleaned_params) # need to validate the changes first (before saving to the database) otherwise the photo gets deleted/updated even if the form validation fails.

    if @pattern.valid?
      @pattern.restore_attributes

      attached_photo_in_database = ActiveStorage::Attachment.find_by(record_id: @pattern.id, record_type: @pattern.class.name)

      if attached_photo_in_database && cleaned_params[:photo] || attached_photo_in_database && cleaned_params[:delete_photo]
        attached_photo_in_database.purge # purge the old attachment (will also delete the blob and the image on cloudinary)
      end
    end

    if @pattern.update(cleaned_params.except(:delete_photo))
      redirect_to patterns_path(anchor: @pattern.id), notice: "Pattern succesfully edited."
    else
      # TODO reload the photo from the database so it's up-to-date (how?) which would replace the photo_key_from_database and photo_in_database? methods I use in the pattern form view

      render :edit
      #redirect_to patterns_path(anchor: @pattern.id), notice: "Something went wrong. Please try again."
    end
    authorize @pattern
  end

  def destroy
    @pattern = Pattern.find(params[:id])
    project_count = @pattern.projects.count
    shopping_item_count = @pattern.shopping_items.count
    authorize @pattern
    if @pattern.destroy
      unless !@pattern.photo.attached?
        @pattern.photo.purge
      end
      redirect_to patterns_path, notice: pattern_delete_success_message(project_count, shopping_item_count)
    else
      redirect_to patterns_path, notice: "Something went wrong. Please try again."
    end
  end

  private

  def pattern_params
    params.require(:pattern).permit(:title, :designer, :fabric_type, :pattern_url, :garment_category_id, :notes, :photo, :delete_photo, :purchased)
  end

  def clean(params)
    if params[:photo] && params[:delete_photo]
      cleaned_params = params.dup
      cleaned_params.delete :photo
      cleaned_params.delete :delete_photo
    else
      cleaned_params = params
    end
    cleaned_params
  end

  def pattern_delete_success_message(project_count, shopping_item_count)
    if project_count == 0
        "Pattern deleted."
    else
      "Pattern, #{project_count} #{'project'.pluralize(project_count)} and #{shopping_item_count} #{'shopping item'.pluralize(shopping_item_count)} deleted."
    end
  end
end

app/views/patterns/_pattern.html.erb
<div class="pattern-details">
  <p>
    <% if @pattern.purchased %>
      <% if @pattern.pattern_url.empty? %>
        <i class="fas fa-check-circle yellow-font bigger"></i>
        You own this pattern. Add a pattern url to remember where you bought it.
      <% else %>
        <i class="fas fa-check-circle green-font bigger"></i>
        You own this pattern and bought it <%= link_to "here", @pattern.full_pattern_url, target: "_blank", class: "pattern-url-link" %>.
      <% end %>
    <% else %>
      <% if @pattern.pattern_url.empty? %>
        <i class="fa fa-frown red-font bigger"></i>
        You don't own this pattern yet. Add a pattern url to remember where you can buy it.
      <% else %>
        <i class="fas fa-shopping-basket yellow-font bigger"></i>
        You don't own this pattern yet. Buy it <%= link_to "here", @pattern.full_pattern_url, target: "_blank", class: "pattern-url-link" %>.
      <% end %>
    <% end %>
  </p>

  <% unless @pattern.notes.empty?  %>
    <p><%= @pattern.notes %></p>
  <% end %>

  <div class="flex-box-three-btns">
    <%= link_to "Start Project", new_project_path(pattern_id: @pattern.id), class: "btn-basic btn-light-blue-ghost" %>
    <%= link_to "Edit", edit_pattern_path(@pattern), class: "btn-basic btn-light-blue-ghost" %>
    <%= link_to "<i class='far fa-trash-alt'></i>".html_safe,
      pattern_path(@pattern),
      method: :delete,
      data: { confirm: pattern_delete_confirm_message(@pattern) },
      class: "delete-icon black-font" %>
      </div>
</div>

app/views/patterns/edit.html.erb
<h1>Edit Pattern</h1>
<%= render 'shared/pattern_form' %>

app/views/patterns/index.html.erb
<h1>Your Patterns</h1>
<%= render partial: 'shared/search_form', locals: { url: "/patterns", placeholder: "Search for title or designer", background_color: "grey-background" } %>

<div class="flex-box top-margin">
  <% if filter_name.nil? || filter_name == "" %>
    <h2>Patterns</h2>
  <% else %>
    <h2><%= filter_name.capitalize %></h2>
  <% end %>
  <div class="margin-left">
    <%= "#{@patterns.count} #{'result'.pluralize(@patterns.count)}" %>
  </div>
</div>

<div class="cards-container-shared">
  <% @patterns.each do |pattern| %>
    <div class="wrapper-pattern-card card-shared" data-image=<%= pattern.custom_image_tag %> >

      <div class="pattern-card" id="<%= pattern.id %>">
        <div>
        <%= link_to pattern_path(pattern), remote: true do %>
          <h3><%= pattern.title %></h3>
        <% end %>
          <p><%= pattern.designer %></p>
          <div class="label-tag fabric-type fixed-width"><%= pattern.fabric_type %></div>
        </div>
        <%= image_tag "#{pattern.garment_category.image_path}", class: "garment-category-icon", id: "#{pattern.garment_category.normalised_name}" %>
      </div>
      <span class="pattern-image-overlay"></span>
    </div>
  <% end %>
</div>

app/views/patterns/new.html.erb
<h1>New Pattern</h1>
<%= render 'shared/pattern_form' %>

app/views/patterns/show.js.erb
var patternCard = document.getElementById("<%= @pattern.id %>");
  if (patternCard.classList.contains("opened")) {
    patternCard.nextElementSibling.remove();
  } else {
    patternCard.insertAdjacentHTML('afterend', "<%= j render(@pattern) %>");
  };
  patternCard.classList.toggle("opened");